version: '3.8'

services:
  pib-sdk:
    build:
      context: .
      dockerfile: Dockerfile  # Build from our updated Dockerfile
    container_name: pib-sdk-container
    volumes:
      # Persist any notebooks if needed
      - pib-data:/app/notebooks
    ports:
      # Expose ports for web applications and Jupyter
      - "8000:8000"   # PIB SDK API
      - "8080:8080"   # Alternative web service
      - "8888:8888"   # Jupyter Notebook/Lab
      - "11311:11311" # ROS2 Discovery (legacy port for compatibility)
      - "4200:4200"   # Cerebra Angular Frontend
      - "4201:4201"   # Digi-Twin Studio Angular Frontend
      - "3001:3001"   # CORS Proxy Server for Onshape API
    environment:
      - PYTHONPATH=/app:/opt/ros/jazzy/lib/python3.11/site-packages:/opt/pib-venv/lib/python3.11/site-packages
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedx_cpp
      - DISPLAY=${DISPLAY:-:0}  # For GUI applications if needed
      - NODE_ENV=development
    # Uncomment if you need GPU access
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # The updated Dockerfile starts both Cerebra and Digi-Twin Studio
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - pib-network



volumes:
  pib-data:

networks:
  pib-network:
    driver: bridge